method: bayes  # Can be 'grid', 'random', or 'bayes'
metric:
  name: eval/f1
  goal: maximize

parameters:
  learning_rate:
    values: [2e-4, 3e-4, 4e-4]
  batch_size:
    values: [8,16]
  num_train_epochs:
    values: [10]
  adapter_config_name:
    values: [houlsby] # houlsby, pfeiffer
  #Fusion Layer specific params
  num_train_epochs_fusion:
    values: [5,10]

run_cap: 20
program: train_adapters.py

command:
  - ${env}
  - python
  - ${program}